version: '3.4'

services:
  ping-app:
    ports:
      - "4001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_HTTP_PORTS=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_SERVICE_NAME=PingApp
  pong-app:
    ports:
      - "4002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_HTTP_PORTS=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_SERVICE_NAME=PongApp